
# Basic
name:               "LI Lab"
title:              "Li lab at USDA-ARS WHGQ"
description:        "this is a page for Xianran Li Lab at the USDA-ARS WHGQ"

#avatar:             "/images/logo/ars-color-lockup.png"
logo:               /images/logo/ars-color-lockup.png

# URL
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "research"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "resources"
    href:           "/resources"
#  - name:           "others"
#    href:           "/blog"



# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"



collections:
  people:
    output: true
    permalink: /people/:title/index.html
